import esbuild from "esbuild";
import process from "process";
import path from "path";
import fs from "fs";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/
`;

const prod = process.argv[2] === "production";

// Output directory (override with OUTDIR; defaults to the project root).
// Useful for building directly into an Obsidian plugins folder.
const outDir = process.env.OUTDIR ?? ".";
const outfile = path.join(outDir, "main.js");

// Copy the static files required for plugin distribution to the output directory.
function copyAssets() {
  if (outDir === ".") return;
  fs.mkdirSync(outDir, { recursive: true });
  for (const asset of ["manifest.json", "styles.css"]) {
    if (fs.existsSync(asset)) {
      fs.copyFileSync(asset, path.join(outDir, asset));
    }
  }
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    ...builtinModules.map((m) => `node:${m}`),
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile,
});

if (prod) {
  await context.rebuild();
  copyAssets();
  process.exit(0);
} else {
  copyAssets();
  await context.watch();
}
