/**
 * Interoperability between the Python API (Script/mdx_chart.py) and the plugin.
 *
 * Two independent implementations of the same file format. If they drift, a chart generated by an
 * agent or a script silently fails to open in Obsidian — or worse, opens with fields dropped. So
 * this checks the REAL output of the real script against the plugin's own parser.
 */
import { parseChartFromText } from '../src/mdx';
import { findCell } from '../src/geometry';
import { execFileSync } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

const API = '/home/wang/wk/Script/mdx_chart.py';
const tmp = (): string => fs.mkdtempSync(path.join(os.tmpdir(), 'qc-api-'));
/** Invoke the CLI. `args` must start with the subcommand. */
const run = (...args: string[]): string =>
  execFileSync('python3', [API, ...args], { encoding: 'utf8' });

let dir: string;
beforeEach(() => { dir = tmp(); });
afterEach(() => { fs.rmSync(dir, { recursive: true, force: true }); });

describe('files written by Script/mdx_chart.py are readable by the plugin', () => {
  it('parses a CLI-created chart', () => {
    const p = path.join(dir, 'cli.mdx');
    run('create', '--path', p, '--title', 'From CLI', '--x-label', 'Reach', '--y-label', 'Cost',
        '--columns', '3', '--rows', '3', '--x-min', '-5', '--x-max', '5', '--y-min', '0', '--y-max', '20');
    const c = parseChartFromText(fs.readFileSync(p, 'utf8'))!;
    expect(c).not.toBeNull();
    expect(c.title).toBe('From CLI');
    expect(c.x.label).toBe('Reach');
    expect(c.x.min).toBe(-5);
    expect(c.y.max).toBe(20);
    expect(c.grid).toEqual({ columns: 3, rows: 3 });
  });

  it('parses cells added via set-cell, palette names resolved to hex', () => {
    const p = path.join(dir, 'cells.mdx');
    run('create', '--path', p)
    run('set-cell', '--path', p, '--col', '1', '--row', '1', '--label', 'Do now', '--color', 'red')
    run('set-cell', '--path', p, '--col', '0', '--row', '0', '--label', 'Later', '--color', 'green')
    const c = parseChartFromText(fs.readFileSync(p, 'utf8'))!;
    expect(findCell(c, 1, 1)?.label).toBe('Do now');
    expect(findCell(c, 1, 1)?.color).toBe('#d93025');   // "red" resolved
    expect(findCell(c, 0, 0)?.color).toBe('#188038');   // "green" resolved
  });

  it('parses items added via add-item', () => {
    const p = path.join(dir, 'items.mdx');
    run('create', '--path', p, '--x-min', '0', '--x-max', '10', '--y-min', '0', '--y-max', '10')
    run('add-item', '--path', p, '--text', 'First label', '--x', '7.5', '--y', '2')
    run('add-item', '--path', p, '--text', 'Second 标签', '--x', '1', '--y', '9')
    const c = parseChartFromText(fs.readFileSync(p, 'utf8'))!;
    expect(c.items.map((i) => i.text)).toEqual(['First label', 'Second 标签']);
    expect(c.items[0].x).toBe(7.5);
    expect(c.items[1].id).toBeTruthy();
  });

  it('preserves unicode and the body across script edits', () => {
    const p = path.join(dir, 'uni.mdx');
    run('create', '--path', p, '--body', '# 标题\n\n优先级 · 紧急 ✅')
    run('add-item', '--path', p, '--text', '中文标签', '--x', '5', '--y', '5')
    const text = fs.readFileSync(p, 'utf8');
    expect(text).toContain('中文标签');
    expect(text).toContain('优先级 · 紧急 ✅');
    expect(parseChartFromText(text)!.items[0].text).toBe('中文标签');
  });

  it('does not destroy notes written under an existing chart', () => {
    const p = path.join(dir, 'body.mdx');
    run('create', '--path', p)
    fs.appendFileSync(p, '\nHand-written note that must survive.\n', 'utf8');
    run('add-item', '--path', p, '--text', 'x', '--x', '1', '--y', '1');
    expect(fs.readFileSync(p, 'utf8')).toContain('Hand-written note that must survive.');
  });

  it('the CLI reports a chart as JSON', () => {
    const p = path.join(dir, 'show.mdx');
    run('create', '--path', p, '--title', 'Inspectable')
    run('add-item', '--path', p, '--text', 'probe', '--x', '3', '--y', '4')
    const parsed = JSON.parse(run('show', '--path', p));
    expect(parsed.title).toBe('Inspectable');
    expect(parsed.items[0]).toMatchObject({ text: 'probe', x: 3, y: 4 });
  });

  it('refuses to overwrite without --force', () => {
    const p = path.join(dir, 'safe.mdx');
    run('create', '--path', p)
    expect(() => run('create', '--path', p)).toThrow();
    run('create', '--path', p, '--force', '--title', 'Replaced')
    expect(parseChartFromText(fs.readFileSync(p, 'utf8'))!.title).toBe('Replaced');
  });

  it('refuses to touch a file that is not a chart', () => {
    const p = path.join(dir, 'other.mdx');
    fs.writeFileSync(p, '---\ntitle: not a chart\n---\n\nbody\n', 'utf8');
    expect(() => run('add-item', '--path', p, '--text', 'x', '--x', '1', '--y', '1')).toThrow();
  });
});
